apiVersion: v1
kind: Pod
metadata:
  name: app-1
  labels:
    app: app1
spec:
  containers:
  - name: app1
    image: mahmoudah98/node-app1
    ports:
      - containerPort: 3000
---      
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP     

---
apiVersion: v1
kind: Pod
metadata:
  name: app-2
  labels:
    app: app2
spec:
  containers:
  - name: app2
    image: mahmoudah98/node-app2
    ports:
      - containerPort: 3000
---      
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  selector:
    app: app2
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP  